# Generated by Django 4.2.3 on 2023-08-19 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myauth.profile')),
                ('address', models.TextField(blank=True, null=True)),
                ('bank_card', models.CharField(max_length=16)),
            ],
            bases=('myauth.profile',),
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myauth.profile')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
            bases=('myauth.profile',),
        ),
    ]
